### ISSUE TITLE
Some questions about extensions-leaflet-map-dsgvo 

### ISSUE THREAD

**Issue by gcPhil** [hupe13/extensions-leaflet-map-dsgvo#2]
Hi @hupe13 ,

ich probiere momentan dein Plugin "DSGVO Snippet for Extensions for Leaflet Map" aus. Es funktioniert bei mir leider noch nicht alles wie es soll:

**- Aktuell wird zwar die DSGVO-Meldung eingeblendet, aber ein Klick auf "Okay" bewirkt dann nichts. Die Meldung bleibt dauerhaft sichtbar, es erscheint keine Karte.** (Auffällig ist dabei auch, dass die ganze Meldung ein #-Link ist, während der Mauszeiger über dem Button wieder zum normalen Pfeil wird. Keine Ahnung ob das das normale verhalten ist.)
**Ich verwende:**
DSGVO Snippet for Extensions for Leaflet Map - Version 221015
Extensions for Leaflet Map - Version 3.2
Leaflet Map - Version 3.0.5
Theme Avada - Version 7.8.2
WordPress - Version 6.0.3
PHP - Version 8.0.24

Unabhängig davon habe ich auch noch zwei weitere Fragen:
- Benötige ich eigentlich zwingend die "_Extensions for Leaflet Map_" oder reicht es, wenn ich "_Leaflet Map_" und "_DSGVO Snippet for Extensions for Leaflet Map_" zusammen nutze? Oder muss ich beim Extensions-Plugin oder am Leaflet-Code noch irgend etwas einstellen, damit das DSGVO Snippet-Plugin funktioniert?
- Wäre es zukünftig evtl. möglich auch den Button-Text frei wählen zu können? (Ein befreundeter angehender Jurist hat mir "Einverstanden" als klarere Formulierung auf der Webseite vorgeschlagen.)

Beste Grüße
Phil

-----

I am currently trying out your plugin " GDPR Snippet for Extensions for Leaflet Map". Unfortunately, not everything works for me as it should:

**- Currently, the GDPR message is displayed, but a click on "Okay" does nothing. The message remains permanently visible, no map appears. ** (It is also noticeable that the whole message is a # link, while the mouse pointer over the button becomes a normal arrow again. No idea if this is the normal behavior).
**I use:**
GDPR Snippet for Extensions for Leaflet Map - Version 221015
Extensions for Leaflet Map - Version 3.2
Leaflet Map - version 3.0.5
Theme Avada - version 7.8.2
WordPress - version 6.0.3
PHP - version 8.0.24

Regardless, I also have two other questions:
- Do I actually necessarily need the "_Extensions for Leaflet Map_" or is it enough if I use "_Leaflet Map_" and "_DSGVO Snippet for Extensions for Leaflet Map_" together? Or do I have to set anything else in the Extensions-Plugin or in the leaflet-code for the GDPR snippet to work?
- Would it be possible in the future to choose the button text freely? (A lawyer friend of mine suggested "Agree" as a clearer wording on the website).

**Comment by hupe13** [comment]
- Es funktioniert auch ohne die Extensions (sollte es jedenfalls).
- Button Text: -> Wunschliste
- Hast du einen Link zu einer Testseite? Gern auch per Mail, siehe leafext.de/doku/about/

**Comment by gcPhil** [comment]
**Vielen Dank noch einmal für die schnell und hilfreiche Rückmeldung.**
Das Problem lag an einem fälschlicherweise das Kartenelement umgebenden #-Link in meinem Design. Jetzt funktioniert alles wie es soll.

**Comment by hupe13** [comment]
> Button Text: -> Wunschliste

Erledigt.

**Comment by gcPhil** [comment]
> > Button Text: -> Wunschliste
> Erledigt.

👍
