### ISSUE TITLE
Multi-Language

### ISSUE THREAD

**Issue by cn-tools** [hupe13/extensions-leaflet-map-dsgvo#3]
Hallo!

Ich nutze dieses Plug-In bereits bei einer Page und es funktioniert genau so wie es soll => **DANKE**

Nun stehe ich vor der Herausforderung, das bei einer weiteren Page umzusetzen. Hier kommt aber der Umstand hinzu, dass diese Page mehrsprachig sein wird.

Dazu habe ich mich entschieden das Plug-In [polylang](https://de.wordpress.org/plugins/polylang/) in der Free-Version zu nutzen.

Gibt es eine Möglichkeit, dass die in deinem Plug-In definierten Text mittels 'polylang' übersetzt werden können?

**Comment by hupe13** [comment]
Die Originalsprache ist wie üblich englisch. Ich verwende [Loco Translate](https://de.wordpress.org/plugins/loco-translate/), um zu übersetzen und die Dateien unter [/lang/](https://github.com/hupe13/extensions-leaflet-map-dsgvo/tree/main/lang) zu erzeugen. Aber mit Polylang sollte das auch funktionieren, ich kenne das Plugin nicht. Wenn du mir die .po und .mo Dateien zukommen lässt, kann ich die in das Plugin integrieren, da haben auch andere was davon.

Im Plugin Extensions for Leaflet Map wurde mir für `elevation` im Frontend [schwedisch](https://github.com/hupe13/extensions-leaflet-map-github/tree/main/lang) zugearbeitet, siehe [Hinweis](https://leafext.de/doku/elevation/) im Backend. Das könnte dich vielleicht auch interessieren.

([Mailadresse](https://leafext.de/doku/about/))

**Comment by hupe13** [comment]
Frage: Hat diese mehrsprachige Page nur ein Backend? Oder hat jede Sprache ihr eigenes?

**Comment by cn-tools** [comment]
> Frage: Hat diese mehrsprachige Page nur ein Backend? Oder hat jede Sprache ihr eigenes?

Es gibt nur ein Backend und über einen Sprachen-Switch im Menü kann zwischen den Sprachen hin und her geschaltet werden.

Das ging aus meinem ersten Post eventuell leider nicht klar heraus: Mir geht es um diese 2 Texte, welche ich im Backend selber festlegen kann:
![image](https://github.com/hupe13/extensions-leaflet-map-dsgvo/assets/6672343/5d311a27-38f4-44d0-a7e7-53dca54535f1)

**Comment by hupe13** [comment]
Das war mir schon klar. Aber mit dieser deiner Konfiguration funktioniert es nicht wie von mir vorgeschlagen. Mit Loco Translate wüsste ich einen Ansatz, dazu müsste ich im Plugincode eine Abfrage ändern.
Ich muss mir mal Polylang ansehen.

**Comment by hupe13** [comment]
Das sieht gut aus: https://de.wordpress.org/plugins/theme-translation-for-polylang/
In den Einstellungen für TTfP nur das Plugin leafext-dsgvo auswählen und dir werden die zu übersetzenden Texte angezeigt.
Aber auch da sehe ich, dass ich "eine Abfrage" ändern muss.

**Comment by hupe13** [comment]
Ich muss nichts ändern. TTfP verwendet keine .mo und .po-Dateien, sondern schreibt die Übersetzungen in die Datenbank.

**Comment by cn-tools** [comment]
Dankeschön für die Info!
Ich werde mir das Heute od. Morgen ansehen und dann hier eine Rückmeldung hinterlassen.

**Comment by cn-tools** [comment]
Ich habe mir das nun angesehen und dabei ist mir folgendes aufgefallen:

- Der Content für den "Submit-Button" kann mit TTfP nicht übersetzt werden
- Der Content für "Text" kann zwar mit TTfp übersetzt werden, jedoch wird der nur dann genutzt, wenn in diesem Plug-In selber der Content von Text "rausgelöscht" wird. Wird dann aber z.B. der Wert für das Cookie-Lifetime geändert und gespeichert OHNE dabei den Content von Text wieder raus zu löschen, so wird dann der übersetzte Text nicht mehr genutzt.

Der Vollständigkeit halber - Sinnhaftigkeit sei dahin gestellt :wink::

- Die zu nutzende URL für das MAP-Image kann nicht mit TTfP angepasst werden
- Der Wert von Cookie-Lifetime kann nicht angepasst werden
- 'each map/only first' kann ebenfalls nicht angepasst werden

**Comment by hupe13** [comment]
Dank deines Hinweises habe ich noch mal alle möglichen Strings betreffs Übersetzung überprüft und einige Fehler gefunden. Danke.  Veröffentlichung folgt.

Ich habe TTfP auch getestet und herausgefunden, dass es nicht wirklich für diesen Zweck funktioniert.
Also doch Loco Translate.

**Comment by hupe13** [comment]
Ich habe alles neu überarbeitet, nun scheint es doch mit TTfP zu funktionieren. Ich muss noch testen.

**Comment by cn-tools** [comment]
> Ich habe alles neu überarbeitet, nun scheint es doch mit TTfP zu funktionieren. Ich muss noch testen.

Gerne helfe ich beim testen :wink: wenn es gewünscht ist.

**Comment by cn-tools** [comment]
Hat jetzt ein paar Tage gedauert -> **DANKE** @hupe13 : jetzt funktioniert das Übersetzen der einzelnen Texte in die diversen Sprachen mittels [TTfP](https://de.wordpress.org/plugins/theme-translation-for-polylang)
💪
